name: "LayerSentry P1 POC"
description: "Nodegroup configuration for general workloads"
family: "layersentry-poc"
supported_k8s_versions:
  - v1.36.4

user_inputs:
  - name: count
    description: "Number of Worker nodes"
    type: number
    mandatory: true
    match:
      type: number
      values:
        min: 0
        max: 60
  - name: cpu
    description: "CPU cores per Worker node"
    type: number
    mandatory: true
    default: 1
    match:
      type: number
      values:
        min: 1
  - name: vcpu
    description: "Number of VCPUs per Worker node"
    type: number
    mandatory: true
    match:
      type: number
      values:
        min: 1
  - name: memory
    description: "RAM in MB per Worker node"
    type: number
    mandatory: true
    match:
      type: number
      values:
        min: 2048
  - name: disk_size
    description: "Disk size in MB per Worker node"
    type: number
    mandatory: true
    match:
      type: number
      values:
        min: 4096

  - name: node_image_id
    description: "Approved node image ID"
    type: number
    mandatory: true
    match:
      type: number
      values:
        min: 0
  - name: system_datastore_id
    description: "Local system datastore ID"
    type: number
    mandatory: true
    match:
      type: number
      values:
        min: 0

flavours:
  small:
    label: "Small Worker Nodes"
    description: |
      <p>Small worker node profile for lightweight workloads.</p>
    override_defaults: false
    defaults:
      cpu: 2
      vcpu: 2
      memory: 4096
      disk_size: 16384

metadata:
  fireedge: